version: '3.9'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: puser
      MB_DB_PASS: "$uP3rStr0nG!P"
      MB_DB_HOST: 165.232.139.165
      JAVA_TOOL_OPTIONS: "-Xmx2g"

networks:
  default:
    name: metabase-network

volumes:
  postgres_data:
    name: metabase_postgres_data
  metabase_data:
    name: metabase_app_data 