version: '3.9'

services:
  metabase:
    image: metabase/metabase:v0.45.0
    container_name: metabase
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase123
      MB_DB_HOST: postgres
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    volumes:
      - ./metabase-data:/metabase-data
    networks:
      - metabase-network
    healthcheck:
      test: curl --fail http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: metabase-postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase123
      POSTGRES_DB: metabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - metabase-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local

networks:
  metabase-network:
    driver: bridge 